economy:
  enabled: true
  constantPay: 0.0
  linearMultiplier: 1.0
removePlayedGames: 10
types:
  ffa:
    name: Free For All
    plugin: mg
  tdm:
    name: Team Deathmatch
    plugin: mg
commands:
  unknown:
    join: mg join
    quit: mg quit
  mg:
    join: mg join
    quit: mg quit
  bh:
    join: bh join
    quit: bh leave