name: ${project.name}
version: ${project.version}-b${build.number}
description: ${project.description}

author: RobotoRaccoon
main: ${project.groupId}.${project.artifactId}.mMain
website: ${organization.url}

depend: [Minigames]
softdepend: [BlockHunt, Vault]

permissions:
  fng.player:
    default: true
    description: Ability to use basic commands.
  fng.host:
    default: op
    description: Ability to use the game commands.
  fng.operator:
    default: op
    description: Ability to use all commands.

commands:
   fng:
      description: Allows you to view reload the config.
      aliases: fridaynightgames
      usage: |
        /<command> help : Shows the help section.